---
title: 'Projet Data Science: Analyse des données'
output:
  pdf_document: default
  html_notebook: default
---

Anova qui montre que le thème et le moment de la journée ont un effet sur la taille du sujet

```{r}
library(FactoMineR)
library(dplyr)

# Anova qui montre que le thème et le moment de la journée ont un effet sur la taille du sujet

dataset <- read.csv("C:/Users/imadl/Desktop/IG4/ProjetDataScience/df3.csv")
df <- subset(dataset,select = c(Moment, subject_size,theme))
df$Moment <- factor(df$Moment)
df$theme <- factor(df$theme)
anov <- aov(df$subject_size~df$Moment*df$theme)
summary(anov)
```


AFC pour mettre en évidence une correlation entre le thème du mail et le moment de la journée
```{r}
df2 <- subset(dataset,select = c(Moment,theme))%>%
 mutate(Moment = factor(Moment, levels = c(1,2,3,4), labels = c('Morning', 'Afternoon','Evening','Night')))
cont <- table(df2)
print(cont)
AFC <- CA(cont)
summary(AFC)
```
AFC pour mettre en évidence une correlation entre la taille du mail et le thème
```{r}
dataset_quali <- read.csv("C:/Users/imadl/Desktop/IG4/ProjetDataScience/df9.csv")
df3 <- subset(dataset_quali,select = c(size_mail_quali,theme))
cont <- table(df3)
AFC2 <- CA(cont)
summary(AFC2)
```

